Add tk to mac for github build
Summary:
The Mac version of cpython is not building on github due to a missing dependency on tk.

Error:  _tkinter failed to import: dlopen(/Users/runner/work/ft_utils/ft_utils/cpython/build/lib.macosx-14.7-arm64-3.13/_tkinter.cpython-313t-darwin.so, 0x0002): Library not loaded: /opt/homebrew/opt/tcl-tk/lib/libtk8.6.dylib

Reviewed By: alexmalyshev

Differential Revision: D66957214

fbshipit-source-id: 3df914ec4267beceafcef2d06cf02a719f868202